world-name: DefaultMap
about:
    author: TheMolkaPL
    version: 1.0
    description: The default look of PGM
max-players: 25
spawn-kit: [272, 261, 278, 320, 397, 262]
teams:
    blue:
        name: Blue Team
        spawn:
            x: -0
            y: 64
            z: -0
            yaw: 0
            pitch: 0
        core:
            x: -0
            y: 64
            z: -0
    red:
        name: Red Team
        spawn:
            x: 0
            y: 64
            z: 0
            yaw: 0
            pitch: 0
        core:
            x: 0
            y: 64
            z: 0